/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DemoIndexRouteImport } from './routes/demo/index'
import { Route as DemoStoreRouteImport } from './routes/demo/store'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as DemoApiUploadsRouteImport } from './routes/demo/api.uploads'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoStartMailWorkerRouteImport } from './routes/demo/start.mail-worker'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartUploadsRouteImport } from './routes/demo/start.uploads'
import { Route as DemoExampleGuitarsIndexRouteImport } from './routes/demo/example.guitars/index'
import { Route as DemoExampleGuitarsGuitarIdRouteImport } from './routes/demo/example.guitars/$guitarId'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'

const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/demo/',
  path: '/demo/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStoreRoute = DemoStoreRouteImport.update({
  id: '/demo/store',
  path: '/demo/store',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiUploadsRoute = DemoApiUploadsRouteImport.update({
  id: '/demo/api/uploads',
  path: '/demo/api/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartMailWorkerRoute = DemoStartMailWorkerRouteImport.update({
  id: '/demo/start/mail-worker',
  path: '/demo/start/mail-worker',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartUploadsRoute = DemoStartUploadsRouteImport.update({
  id: '/demo/start/uploads',
  path: '/demo/start/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoExampleGuitarsIndexRoute = DemoExampleGuitarsIndexRouteImport.update({
  id: '/demo/example/guitars/',
  path: '/demo/example/guitars/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoExampleGuitarsGuitarIdRoute =
  DemoExampleGuitarsGuitarIdRouteImport.update({
    id: '/demo/example/guitars/$guitarId',
    path: '/demo/example/guitars/$guitarId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/demo/store': typeof DemoStoreRoute
  '/demo/': typeof DemoIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/uploads': typeof DemoApiUploadsRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/mail-worker': typeof DemoStartMailWorkerRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/uploads': typeof DemoStartUploadsRoute
  '/demo/example/guitars/$guitarId': typeof DemoExampleGuitarsGuitarIdRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/example/guitars/': typeof DemoExampleGuitarsIndexRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/demo/store': typeof DemoStoreRoute
  '/demo': typeof DemoIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/uploads': typeof DemoApiUploadsRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/mail-worker': typeof DemoStartMailWorkerRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/uploads': typeof DemoStartUploadsRoute
  '/demo/example/guitars/$guitarId': typeof DemoExampleGuitarsGuitarIdRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/example/guitars': typeof DemoExampleGuitarsIndexRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/demo/store': typeof DemoStoreRoute
  '/demo/': typeof DemoIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/uploads': typeof DemoApiUploadsRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/mail-worker': typeof DemoStartMailWorkerRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/uploads': typeof DemoStartUploadsRoute
  '/demo/example/guitars/$guitarId': typeof DemoExampleGuitarsGuitarIdRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/example/guitars/': typeof DemoExampleGuitarsIndexRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/demo/store'
    | '/demo/'
    | '/api/auth/$'
    | '/demo/api/names'
    | '/demo/api/uploads'
    | '/demo/start/api-request'
    | '/demo/start/mail-worker'
    | '/demo/start/server-funcs'
    | '/demo/start/uploads'
    | '/demo/example/guitars/$guitarId'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/example/guitars/'
    | '/demo/start/ssr/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/demo/store'
    | '/demo'
    | '/api/auth/$'
    | '/demo/api/names'
    | '/demo/api/uploads'
    | '/demo/start/api-request'
    | '/demo/start/mail-worker'
    | '/demo/start/server-funcs'
    | '/demo/start/uploads'
    | '/demo/example/guitars/$guitarId'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/example/guitars'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/demo/store'
    | '/demo/'
    | '/api/auth/$'
    | '/demo/api/names'
    | '/demo/api/uploads'
    | '/demo/start/api-request'
    | '/demo/start/mail-worker'
    | '/demo/start/server-funcs'
    | '/demo/start/uploads'
    | '/demo/example/guitars/$guitarId'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/example/guitars/'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DemoStoreRoute: typeof DemoStoreRoute
  DemoIndexRoute: typeof DemoIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoApiUploadsRoute: typeof DemoApiUploadsRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartMailWorkerRoute: typeof DemoStartMailWorkerRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartUploadsRoute: typeof DemoStartUploadsRoute
  DemoExampleGuitarsGuitarIdRoute: typeof DemoExampleGuitarsGuitarIdRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoExampleGuitarsIndexRoute: typeof DemoExampleGuitarsIndexRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/demo/': {
      id: '/demo/'
      path: '/demo'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/store': {
      id: '/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof DemoStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/uploads': {
      id: '/demo/api/uploads'
      path: '/demo/api/uploads'
      fullPath: '/demo/api/uploads'
      preLoaderRoute: typeof DemoApiUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/mail-worker': {
      id: '/demo/start/mail-worker'
      path: '/demo/start/mail-worker'
      fullPath: '/demo/start/mail-worker'
      preLoaderRoute: typeof DemoStartMailWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/uploads': {
      id: '/demo/start/uploads'
      path: '/demo/start/uploads'
      fullPath: '/demo/start/uploads'
      preLoaderRoute: typeof DemoStartUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/example/guitars/': {
      id: '/demo/example/guitars/'
      path: '/demo/example/guitars'
      fullPath: '/demo/example/guitars/'
      preLoaderRoute: typeof DemoExampleGuitarsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/example/guitars/$guitarId': {
      id: '/demo/example/guitars/$guitarId'
      path: '/demo/example/guitars/$guitarId'
      fullPath: '/demo/example/guitars/$guitarId'
      preLoaderRoute: typeof DemoExampleGuitarsGuitarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr/'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  DemoStoreRoute: DemoStoreRoute,
  DemoIndexRoute: DemoIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoApiUploadsRoute: DemoApiUploadsRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartMailWorkerRoute: DemoStartMailWorkerRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartUploadsRoute: DemoStartUploadsRoute,
  DemoExampleGuitarsGuitarIdRoute: DemoExampleGuitarsGuitarIdRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoExampleGuitarsIndexRoute: DemoExampleGuitarsIndexRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
